### ISSUE TITLE
微调内存占用

### ISSUE THREAD

**Issue by surviveMiao** [JL-er/RWKV-v5-lora#1]
您好，请问微调v5 7b模型需要多少内存？我微调1.5b用了40g  128g内存连3b都无法进行微调

**Comment by JL-er** [comment]
lora 24g显存  64g内存就可以了。如果全量可能需要160g内存 注意deepspeed策略

**Comment by surviveMiao** [comment]
> lora 24g显存 64g内存就可以了。如果全量可能需要160g内存 注意deepspeed策略

您好，我使用的就是咱们的这个lora微调代码，请问 deepspeed策略是deepspeed_stage_2 这样不是全量微调对吗？  我128g内存使用deepspeed_stage_2策略连3b模型也无法运行起来， 请问这是因为什么呀？我显卡是24*10的，  参数如下图：
![image](https://github.com/JL-er/RWKV-v5-lora/assets/96619920/1a6bdaaa-229b-4797-98b4-cdcba6e7bf9f)

**Comment by JL-er** [comment]
先单卡试试，你现在使用的是8卡

**Comment by surviveMiao** [comment]
> 先单卡试试，你现在使用的是8卡

感谢佬！您说的很正确，我用单卡的话似乎可以跑起来。  原来多卡跑的话，内存会占多份。
7b跑起来之后，大概占17G，在加载的时候占用的会多一些。

**Comment by surviveMiao** [comment]
> 先单卡试试，你现在使用的是8卡

您好，我还想问一下，如果我想要指定显卡跑程序，我应该怎么进行设置？

**Comment by JL-er** [comment]
这个我也不太清楚，可以问问社区的人

**Comment by surviveMiao** [comment]
> 这个我也不太清楚，可以问问社区的人

好的谢谢！
